# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Chris Diana
tagline:             'Web Designer & Developer'
description:         'Useful things found'
url:                 http://cdmedia.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Chris Diana
  url:               http://chrisdianamedia.com
  email:             cdiana.media@gmail.com

# Custom vars
version:             1.0.0
